AdminDashboardB/Controllers/LanguageController.cs
namespace DTOsB.Controllers
{ public class LanguageController : Controller
    {
    private readonly ILanguageService languageService;

public LanguageController(ILanguageService _languageService){
 languageService = _languageService;
}

 public async Task<IActionResult> Index()
        {

         var availableLanguages = await languageService.GetAllLanguagesAsync();

         if (availableLanguages == null)
            {
                // Handle null case for products
                return View("Error", "No Languages available.");
            }
            return View(availableLanguages);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

         [HttpPost]
          public async Task<IActionResult> Create(LanguageDto langDto){

            var result = await languageService.CreateProductAsync(langDto);
            if (!result.IsSuccess)
            {
                ModelState.AddModelError("", result.Msg);
                return View(langDto);
            }

             return RedirectToAction(nameof(Index));
}

public async Task<IActionResult> Edit(int id)
        {

            var language = await languageService.GetProductByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(language);
        }
        
 [HttpPost]
          public async Task<IActionResult> Edit(int id, ResultView<LanguageDto> resultView){

        var langDto = resultView.Entity;

            if (id != langDto.Id)
            {
                return BadRequest();
            }

             var result = await languageService.UpdateProductAsync(langDto);
}

  public async Task<IActionResult> Delete(int id)
        {
            var lang = await languageService.GetProductByIdAsync(id);
            if (lang == null)
            {
                return NotFound();
            }
            return View(lang);
        }

        // POST: Products/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await languageService.DeleteProductAsync(id);
            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            return BadRequest(result.Msg);
        }
        

    
    }}

AdminDashboardB/Controllers/OrderController.cs
using ApplicationB.Services_B.Order;
using AutoMapper;
using DTOsB.Shared;
using DTOsB.Order.OrderDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DTOsB.Controllers
{
    [Authorize(Roles = "Admin")]

    public class OrderController : Controller
    {
        private readonly IOrderService orderService; // Assuming you're using a service for business logic

        public OrderController(IOrderService _orderService)
        {
            orderService = _orderService;
        }
        //==============All=====================
        public async Task<IActionResult> Index()
        {
            var orders = await orderService.GetAllOrdersAsync();
            return View(orders);
        }

        //==============Add=====================

        public async Task<IActionResult> Add()
        {
            AddOrUpdateOrderBDTO order = new AddOrUpdateOrderBDTO();
            // order.Users = 

            return View("Add", order);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddOrUpdateOrderBDTO orderBDTO)
        {
            /* (ModelState.IsValid)
            {*/
            orderBDTO.OrderDate = DateTime.Now;
            orderBDTO.TotalPrice = 5000;
            orderBDTO.ApplicationUserId = "db0a8336-7f0f-416c-90c8-a8dfd01d97f7";


            await orderService.CreateOrderAsync(orderBDTO);
            return RedirectToAction("Index");
            /*}

            return View(orderBDTO);*/
        }

        //==============Edit=====================

        public async Task<IActionResult> Edit(int id)
        {
            SelectOrderBDTO order = await orderService.GetOrderByIdAsync(id);

            if (order == null || order.CurrentStatus == ModelsB.Order_B.Status.Shipped || order.CurrentStatus == ModelsB.Order_B.Status.Delivered)
            {
                TempData["ErrorMessage"] = "You can't edit this order anymore.";
                return RedirectToAction("Index");
            }
            var updateOrder = new AddOrUpdateOrderBDTO()
            {
                Id = id,
                OrderDate = order.OrderDate,
                TotalPrice = order.TotalPrice,
                CurrentStatus = order.CurrentStatus,
                ApplicationUserId = "db0a8336-7f0f-416c-90c8-a8dfd01d97f7"
            };

            return View("Edit", updateOrder);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AddOrUpdateOrderBDTO orderBDTO)
        {
            if (ModelState.IsValid)
            {
                await orderService.UpdateOrderAsync(orderBDTO);
                return RedirectToAction("Index");
            }

            return View(orderBDTO);
        }

        //==============Details=====================

        public async Task<IActionResult> DetailsOfOrder(int id)
        {
            var order = await orderService.GetOrderByIdAsync(id);
            foreach (var item in order.OrderItems)
            {
                item.TotalPrice = (int)(item.Quantity * item.Price);
            }
            return View("Details", order);
        }

        //==============Cancel=====================

        public async Task<IActionResult> CancelOrder(int id)
        {
            var order = await orderService.GetOrderByIdAsync(id);
            if (order == null || order.CurrentStatus == ModelsB.Order_B.Status.Shipped || order.CurrentStatus == ModelsB.Order_B.Status.Delivered)
            {
                TempData["ErrorMessage"] = "You can't cancel this order anymore.";
                return RedirectToAction("Index");
            }

            await orderService.DeleteOrderAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AdminDashboardB/Controllers/ProductController.cs
using ApplicationB.Contracts_B.General;
using ApplicationB.Services_B;
using ApplicationB.Services_B.Category;
using ApplicationB.Services_B.General;
using ApplicationB.Services_B.Product;
using ApplicationB.Services_B.User;
using DTOsB.Category;
using DTOsB.Product;
using DTOsB.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ModelsB.Category_B;
using ModelsB.Localization_B;
using ModelsB.Product_B;
using PayPalCheckoutSdk.Orders;

namespace DTOsB.Controllers
{
    //[Authorize(Roles = "Admin")]

    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IImageService _imageService;
        private readonly ILanguageService languageService;
        private readonly IUserService _userService;
        private readonly IProductService productService;
        private readonly IProductImageService _productImageService;
        private readonly IProductSpecificationService _productSpecificationService;
        private readonly IProductTranslationService _productTranslationService;
        private readonly IProductSpecificationTransService _productSpecificationTransService;
        private readonly ICategoryService categoryService;
        private readonly IProductCategoryService productCategoryService;


        public ProductController(IProductService _productService, IUserService userService, ILanguageService _languageService, IProductImageService productImageService, IProductSpecificationService productSpecificationService,
            IProductTranslationService productTranslationService, IProductSpecificationTransService productSpecificationTransService, IImageService imageService, ICategoryService _categoryService, IProductCategoryService _productCategoryService)
        {
            productService = _productService;
            _imageService = imageService;
            _userService = userService;
            languageService = _languageService;
            _productImageService = productImageService;
            _productSpecificationService = productSpecificationService;
            _productTranslationService = productTranslationService;
            _productSpecificationTransService = productSpecificationTransService;
            categoryService = _categoryService;
            productCategoryService = _productCategoryService;
        }


        public async Task<IActionResult> Index(string searchString, int? selectedLanguageId, int? selectedCategoryId)
        {
            ViewBag.SearchString = searchString;



            var availableLanguages = await languageService.GetAllLanguagesAsync();
            ViewBag.AvailableLanguages = availableLanguages;

            if (selectedLanguageId.HasValue && selectedLanguageId > 0)
            {
                await languageService.SetUserSelectedLanguageAsync((int)selectedLanguageId);
            }
            ViewBag.SelectedLanguageId = selectedLanguageId;

            var categories = await categoryService.GetAllCategoriesAsync();
            ViewBag.Categories = categories.Entity;
            ViewBag.SelectedCategoryId = selectedCategoryId;

            var products = await productService.GetAllProductsAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                products = await productService.SearchProductsByNameAsync(searchString);
            }



            if (selectedCategoryId > 0)
            {
                var productsByCategory = productCategoryService.GetProductsByCategoryIdAsync((int)selectedCategoryId).Result.Entity;

                // Initialize _Products.Entity as IEnumerable<ProductDto>
                var _Products = new ResultView<IEnumerable<ProductDto>>()
                {
                    Entity = new List<ProductDto>() // Ensure Entity is initialized
                };

                foreach (var item in productsByCategory)
                {
                    _Products.Entity = _Products.Entity.Append(item.Product);
                }

                return View(_Products);
            }

            if (products == null)
            {
                // Handle null case for products
                return View("Error", "Products not available.");
            }
            return View(products);
        }


        //public async Task<IActionResult> Index(int pageNumber = 1, int count = 10, int selectedLanguageId = 2)
        //{
        //    var products = await productService.GetAllPaginatedByLanguageAsync(pageNumber, count, selectedLanguageId);
        //    var availableLanguages = await languageService.GetAllLanguagesAsync();

        //    var viewModel = new ProductViewModelWithLang
        //    {
        //        Products = products.Data,
        //        AvailableLanguages = availableLanguages,
        //        SelectedLanguageId = selectedLanguageId
        //    };

        //    return View(viewModel);
        //}

        //public async Task<IActionResult> Index()
        //{
        //    var products = await productService.GetAllProductsAsync();
        //    return View(products); // Assuming Data contains IEnumerable<ProductViewModel>
        //}

        // GET: Products/Create



        public async Task<IActionResult> Create()
        {

            var categories = await categoryService.GetAllCategoriesAsync();
            ViewBag.Categories = categories.Entity;

            return View();
        }

        // POST: Products/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateOrUpdateDto productDto, List<GetAllCategoriesDTO> SelectedCategories)
        {
            //if (ModelState.IsValid)
            //{

            productDto.CreatedBy = _userService.GetAppUserByIdAsync(_userService.GetCurrentUserId()).Result.UserName;
            productDto.UpdatedBy = _userService.GetAppUserByIdAsync(_userService.GetCurrentUserId()).Result.UserName;



            var result = await productService.CreateProductAsync(productDto);
            if (!result.IsSuccess)
            {
                ModelState.AddModelError("", result.Msg);
                return View(productDto);
            }


            if (productDto.ImageFiles != null && productDto.ImageFiles.Count > 0)
            {

                result.Entity.Images = result.Entity.Images ?? new List<ProductImageCreateOrUpdateDto>();

                foreach (var imageFile in productDto.ImageFiles)
                {

                    var imageUrl = await _imageService.SaveImageAsync(imageFile, "ImageUrls");


                    var imageDto = new ProductImageCreateOrUpdateDto
                    {
                        Url = imageUrl,
                        ProductId = result.Entity.Id
                    };


                    var imageResult = await _productImageService.AddImageAsync(imageDto);
                    if (!imageResult.IsSuccess)
                    {
                        ModelState.AddModelError("", imageResult.Msg);
                        return View(result.Entity);
                    }
                }
            }


            for (int i = 0; i < SelectedCategories.Count; i++)
            {
                var newItem = new ProductCategoryDto
                {
                    CategoryId = SelectedCategories[i].Id,
                    ProductId = result.Entity.Id,
                    IsMainCategory = (i == 0) ? true : false,
                };
                var Result = await productCategoryService.AddAsync(newItem);

                if (!Result.IsSuccess)
                {
                    ModelState.AddModelError("", Result.Msg);
                    return View(result.Entity);
                }
            }

            //Translations
            //foreach (var trans in productDto.Translations)
            //{
            //    var transResult = await _productTranslationService.AddTranslationAsync(trans);
            //    if (!transResult.IsSuccess)
            //    {
            //        ModelState.AddModelError("", transResult.Msg);
            //        return View(productDto);
            //    }
            //}


            //Specifications
            //foreach (var spec in productDto.Specifications)
            //{
            //    var specResult = await _productSpecificationService.AddSpecificationAsync(spec);
            //    if (!specResult.IsSuccess)
            //    {
            //        ModelState.AddModelError("", specResult.Msg);
            //        return View(productDto);
            //    }

            //    foreach (var specTrans in spec.Translations)
            //    {
            //        var specTransResult = await _productSpecificationTransService.AddTranslationAsync(specTrans);
            //        if (!specTransResult.IsSuccess)
            //        {
            //            ModelState.AddModelError("", specTransResult.Msg);
            //            return View(productDto);
            //        }
            //    }
            //}

            //}
            return RedirectToAction(nameof(Index));
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var allCategories = await categoryService.GetAllCategoriesAsync();
            ViewBag.AllCategories = allCategories.Entity;

            var product = await productService.GetProductByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Edit/5

        //[ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, ResultView<ProductCreateOrUpdateDto> resultView,
            List<GetAllCategoriesDTO> SelectedCategories)
        {

AdminDashboardB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - B_Tech.AdminDashboard</title>
    <link href="~/icons8-admin-16.png" rel="icon" type="image/svg" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/B_Tech.AdminDashboard.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand me-3 ps-3 border rounded" href="http://localhost:5067/" style="background-color:white"><img src="https://btech.com/media/logo/stores/2/new3.png" alt="B.Tech" width="170" /></a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm ms-auto order-1 order-lg-0  me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    @* <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li> *@
                    <li><hr class="dropdown-divider" /></li>
                  <li><a  class="dropdown-item" asp-controller="Admin" asp-action="Logout">Sign Out</a></li>



                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Manage</div>
                        @* <a class="nav-link" asp-controller="Role" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-pen-ruler"></i></div>
                            Roles
                        </a> *@
                        <a class="nav-link" asp-controller="Admin" asp-action="GetAllUsers">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-users-gear"></i></div>
                            Users
                        </a>

                        <div class="sb-sidenav-menu-heading">Website</div>

                        <a class="nav-link" asp-controller="Language" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-layer-group"></i></div>
                            Languages
                        </a>
                        <a class="nav-link" asp-controller="Category" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-layer-group"></i></div>
                            Category
                        </a>
                        <a class="nav-link" asp-controller="Product" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-box-open"></i></div>
                            Products
                        </a>
                        <a class="nav-link" asp-controller="Order" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-cart-shopping"></i></div>
                            Orders
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">This website is:</div>
                    Admin Panel
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2025</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdminDashboardB/Views/Shared/_TransCreate.cshtml
@model DTOsB.Product.ProductTranslationDto



            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LanguageId" class="control-label"></label>
                <select asp-for="LanguageId" class ="form-control" asp-items="ViewBag.LanguageId"></select>
            </div>
          @*   <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
      *@